import { Injectable, Logger } from '@nestjs/common';
import { exec } from 'child_process';
import { promisify } from 'util';
import * as fs from 'fs';
import * as path from 'path';
import simpleGit from 'simple-git';
import { Task } from '../entities/task.entity';
import { TaskCodeDiff } from '../entities/task-code-diff.entity';
import { GitLabService } from '../../gitlab/gitlab.service';
import { IndexingService } from '../../repository/services/indexing.service';
import { CodeContextService } from './code-context.service';

const execAsync = promisify(exec);

export interface ApplyResult {
  changed: boolean;
  appliedFiles: string[];
  changeLog: string[];
}

@Injectable()
export class TaskGitService {
  private readonly logger = new Logger(TaskGitService.name);

  constructor(
    private readonly gitlab: GitLabService,
    private readonly codeContext: CodeContextService,
    private readonly indexing: IndexingService,
  ) {}

  async prepareWorkspace(
    task: Task,
    branchName: string,
    codeDiff: TaskCodeDiff | null,
  ): Promise<string | null> {
    const project = task.project;
    if (!project) return null;

    let clonePath = project.clonePath;
    if (!clonePath || !fs.existsSync(clonePath)) {
      this.logger.warn(`Clone missing for project ${project.id} — cloning on demand`);
      clonePath = await this.indexing.ensureProjectCloned(project.id);
      if (clonePath) project.clonePath = clonePath;
    }
    if (!clonePath || !fs.existsSync(clonePath)) return null;

    const defaultBranch = project.defaultBranch || 'main';
    await this.resetCloneToDefault(clonePath, defaultBranch);

    const git = simpleGit(clonePath);

    const branches = await git.branchLocal();
    if (branches.all.includes(branchName)) {
      await git.checkout(branchName);
      await git.reset(['--hard', defaultBranch]).catch(() => undefined);
    } else {
      await git.checkoutLocalBranch(branchName);
    }

    await this.applyChanges(clonePath, task, codeDiff);
    return clonePath;
  }

  /** Discard local edits from prior tasks — start from clean default branch */
  async resetCloneToDefault(clonePath: string, defaultBranch = 'main'): Promise<void> {
    const git = simpleGit(clonePath);
    await git.fetch().catch(() => undefined);
    await git.checkout(defaultBranch).catch(() => undefined);
    await git.reset(['--hard', defaultBranch]).catch(() => undefined);
    await git.pull('origin', defaultBranch).catch(() => undefined);
    await git.clean('f', ['-d']).catch(() => undefined);
    this.logger.log(`Reset clone to clean ${defaultBranch} at ${clonePath}`);
  }

  buildCommitMessage(task: Task, codeDiff: TaskCodeDiff | null): string {
    const lines = [`[RepoPilot] ${task.taskId}: ${task.requirement.slice(0, 72)}`, ''];
    const edits = codeDiff?.fileEdits || [];
    if (edits.length > 0) {
      lines.push('Changes:');
      for (const edit of edits) {
        for (const comment of edit.changeComments || []) {
          lines.push(`- ${edit.path}: ${comment}`);
        }
      }
      lines.push('');
    } else if (codeDiff?.filesToModify?.length) {
      lines.push('Changes:');
      for (const f of codeDiff.filesToModify) {
        for (const c of f.changes) lines.push(`- ${f.path}: ${c}`);
      }
      lines.push('');
    }
    lines.push(`Requirement: ${task.requirement}`);
    return lines.join('\n');
  }

  buildMrDescription(task: Task, codeDiff: TaskCodeDiff | null, validationSummary?: string): string {
    const parts = [
      `## RepoPilot — ${task.taskId}`,
      '',
      task.requirement,
      '',
      '### Implementation Plan',
      codeDiff?.implementationPlan || 'See dashboard.',
      '',
      '### Code Changes',
    ];
    const edits = codeDiff?.fileEdits || [];
    if (edits.length > 0) {
      for (const edit of edits) {
        parts.push(`#### \`${edit.path}\``);
        for (const c of edit.changeComments || []) parts.push(`- ${c}`);
        parts.push('');
      }
    } else if (codeDiff?.filesToModify?.length) {
      for (const f of codeDiff.filesToModify) {
        parts.push(`#### \`${f.path}\``);
        for (const c of f.changes) parts.push(`- ${c}`);
        parts.push('');
      }
    }
    if (validationSummary) {
      parts.push('### Validation', validationSummary, '');
    }
    parts.push('---', '*Generated by RepoPilot AI Engineering Copilot*');
    return parts.join('\n');
  }

  async hasWorkingTreeChanges(clonePath: string, branchName: string): Promise<boolean> {
    const git = simpleGit(clonePath);
    const branches = await git.branchLocal();
    if (branches.all.includes(branchName)) {
      await git.checkout(branchName);
    }
    const status = await git.status();
    return status.files.length > 0;
  }

  async commitAndPush(
    task: Task,
    branchName: string,
    codeDiff: TaskCodeDiff | null,
  ): Promise<string | null> {
    const project = task.project;
    const clonePath = project?.clonePath;
    if (!project || !clonePath || !fs.existsSync(clonePath)) {
      this.logger.warn(`No clone path for project ${project?.id} — skipping git commit`);
      return null;
    }

    const git = simpleGit(clonePath);

    try {
      let remoteUrl = project.repositoryUrl;
      try {
        remoteUrl = await this.gitlab.buildAuthenticatedCloneUrl(project.repositoryUrl);
      } catch {
        this.logger.warn('No GitLab token — push may fail for private repos');
      }

      const branches = await git.branchLocal();
      if (!branches.all.includes(branchName)) {
        this.logger.warn(`Branch ${branchName} not checked out before commit`);
        return null;
      }

      await git.checkout(branchName);
      let status = await git.status();
      if (status.files.length === 0 && codeDiff) {
        this.logger.warn(`No git changes on ${branchName} — re-applying code diff`);
        const applied = await this.applyChanges(clonePath, task, codeDiff);
        if (!applied.changed) {
          this.logger.warn(`No file changes to commit for ${task.taskId}`);
          return null;
        }
        status = await git.status();
      }
      if (status.files.length === 0) {
        this.logger.warn(`No staged changes for ${task.taskId}`);
        return null;
      }

      await git.add('.');
      await git.commit(this.buildCommitMessage(task, codeDiff));

      const remotes = await git.getRemotes(true);
      if (!remotes.find((r) => r.name === 'origin')) {
        await git.addRemote('origin', remoteUrl);
      } else {
        await git.remote(['set-url', 'origin', remoteUrl]);
      }

      await git.push('origin', branchName, ['--set-upstream', '--force-with-lease']);
      const log = await git.log({ maxCount: 1 });
      return log.latest?.hash || null;
    } catch (error) {
      this.logger.error(`Git commit/push failed: ${(error as Error).message}`);
      return null;
    }
  }

  async applyChanges(
    clonePath: string,
    task: Task,
    codeDiff: TaskCodeDiff | null,
  ): Promise<ApplyResult> {
    const appliedFiles: string[] = [];
    const changeLog: string[] = [];

    if (codeDiff?.fileEdits?.length) {
      for (const edit of codeDiff.fileEdits) {
        const normalized = edit.path.replace(/^\.\//, '');
        const full = path.join(clonePath, normalized);
        const dir = path.dirname(full);
        if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });

        const existing = fs.existsSync(full) ? fs.readFileSync(full, 'utf8') : '';
        if (existing === edit.newContent) {
          this.logger.warn(`Skipping ${normalized} — content already matches (no diff)`);
          continue;
        }

        fs.writeFileSync(full, edit.newContent);
        appliedFiles.push(normalized);
        for (const c of edit.changeComments || []) {
          changeLog.push(`${normalized}: ${c}`);
        }
      }
      if (appliedFiles.length > 0) {
        return { changed: true, appliedFiles, changeLog };
      }
    }

    if (codeDiff?.patchContent?.trim()) {
      const patchFile = path.join(clonePath, `.repopilot-${task.taskId}.patch`);
      fs.writeFileSync(patchFile, codeDiff.patchContent);
      try {
        await execAsync(`git apply --ignore-whitespace "${patchFile}"`, { cwd: clonePath });
        if (fs.existsSync(patchFile)) fs.unlinkSync(patchFile);
        return {
          changed: true,
          appliedFiles: codeDiff.filesToModify?.map((f) => f.path) || [],
          changeLog: changeLog.length ? changeLog : ['Applied unified patch'],
        };
      } catch {
        this.logger.warn(`Patch apply failed for ${task.taskId}`);
        if (fs.existsSync(patchFile)) fs.unlinkSync(patchFile);
      }
    }

    this.logger.error(`No code changes applied for ${task.taskId} — re-run code generation`);
    return { changed: false, appliedFiles: [], changeLog: [] };
  }
}
